<?php

namespace common\models;

use phpDocumentor\Reflection\Types\Self_;
use Yii;
use yii\behaviors\SluggableBehavior;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use kartik\tree\models\Tree;
use kartik\tree\models\TreeTrait;
use yii\db\Query;
use yii\helpers\ArrayHelper;


/**
 * This is the model class for table "Product_category".
 *
 * @property string $id
 * @property string $root
 * @property string $lft
 * @property string $rgt
 * @property integer $lvl
 * @property string $name
 * @property string $icon
 * @property integer $icon_type
 * @property boolean $active
 * @property boolean $selected
 * @property boolean $disabled
 * @property boolean $readonly
 * @property boolean $visible
 * @property boolean $collapsed
 * @property boolean $movable_u
 * @property boolean $movable_d
 * @property boolean $movable_l
 * @property boolean $movable_r
 * @property boolean $removable
 * @property boolean $removable_all
 *
 * @property string $child_allowed [integer]
 * @property int $update_datetime [timestamp]
 */
class Category extends Tree
{


    use \kartik\tree\models\TreeTrait {
        isDisabled as parentIsDisabled; // note the alias
    }

    public $activate;



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%category}}';
    }


    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'name' => 'Категория',
        ];
    }


    public function beforeSave($insert)
    {
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }


    public static function getCategoryList()
    {
        return Category::find()->where(['active' => 1])->addOrderBy('root, lft');
    }

    public static function getBottomCategoryList()
    {
        return Category::find()->where('lvl = 2')->addOrderBy('root, lft');
        #return Yii::$app->db->createCommand("SELECT id,name FROM categories WHERE lft+1=rgt ORDER BY name ASC")->queryAll();
    }


}
