<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "request_favorite".
 *
 * @property int $id
 * @property int $request_id
 * @property int $created_by
 * @property int $created_at
 *
 * @property Request $request
 * @property User $createdBy
 */
class RequestFavorite extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'request_favorite';
    }

    public function fields()
    {
        return ['id', 'request_id', 'created_by', 'created_at', 'createdBy', 'request'];
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['request_id', 'created_by', 'created_at'], 'default', 'value' => null],
            [['request_id', 'created_by', 'created_at'], 'integer'],
            [['request_id'], 'exist', 'skipOnError' => true, 'targetClass' => Request::className(), 'targetAttribute' => ['request_id' => 'id']],
            [['created_by'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['created_by' => 'id']],
            [['request_id', 'created_by'], 'unique', 'targetAttribute' => ['request_id', 'created_by']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'request_id' => 'Request ID',
            'created_by' => 'Created By',
            'created_at' => 'Created At',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRequest()
    {
        return $this->hasOne(Request::className(), ['id' => 'request_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCreatedBy()
    {
        return $this->hasOne(User::className(), ['id' => 'created_by']);
    }

    public function beforeSave($insert)
    {
        if($insert){
            $this->created_by = Yii::$app->user->identity->id;
            $this->created_at = time();
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
