<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "response".
 *
 * @property int $id
 * @property int $request_id
 * @property int $status
 * @property int $offer_id
 * @property int $created_by
 * @property int $created_at
 *
 * @property Request[] $requests
 * @property Offer $offer
 * @property Request $request
 * @property User $createdBy
 */
class Response extends \yii\db\ActiveRecord
{
    public $initial_pay;
    public $total_pay;
    public $period;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'response';
    }

    public function fields()
    {
        return ['id', 'request_id', 'status', 'offer_id', 'created_by', 'created_at', 'offer', 'created_by'];
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            ['status', 'default', 'value' => 1],
            ['created_at', 'default', 'value' => time()],
            ['created_by', 'default', 'value' => Yii::$app->user->identity->id],
            [['request_id', 'initial_pay', 'total_pay', 'period', 'request_id'], 'required'],
            [['request_id', 'status', 'offer_id', 'created_by', 'created_at'], 'integer'],
            [['offer_id'], 'exist', 'skipOnError' => true, 'targetClass' => Offer::className(), 'targetAttribute' => ['offer_id' => 'id']],
            [['request_id'], 'exist', 'skipOnError' => true, 'targetClass' => Request::className(), 'targetAttribute' => ['request_id' => 'id']],
            [['created_by'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['created_by' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'request_id' => 'Request ID',
            'status' => 'Status',
            'offer_id' => 'Offer ID',
            'created_by' => 'Created By',
            'created_at' => 'Created At',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRequests()
    {
        return $this->hasMany(Request::className(), ['accepted_response_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOffer()
    {
        return $this->hasOne(Offer::className(), ['id' => 'offer_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRequest()
    {
        return $this->hasOne(Request::className(), ['id' => 'request_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCreatedBy()
    {
        return $this->hasOne(User::className(), ['id' => 'created_by']);
    }

    public function beforeSave($insert)
    {
        if ($insert) {
            $offer = new Offer();
            $offer->initial_pay = $this->initial_pay;
            $offer->total_pay = $this->total_pay;
            $offer->period = $this->period;
            $offer->request_id = $this->request_id;
            $offer->save();
            $this->offer_id = $offer->id;
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
